### ISSUE TITLE
Failed to load the git-grep package

### ISSUE THREAD

**Issue by silverskyvicto** [mizchi/atom-git-grep#13]
I started Atom. But this error has occurred.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [git-grep](git://github.com/mizchi/atom-git-grep) package, v0.9.0
### Stack Trace

Failed to load the git-grep package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/ey/.atom/packages/git-grep/lib/git-grep-view.coffee:4:199)
    at /Users/ey/.atom/packages/git-grep/lib/git-grep-view.coffee:15:5
    at Object.<anonymous> (/Users/ey/.atom/packages/git-grep/lib/git-grep-view.coffee:75:5)
    at Object.<anonymous> (/Users/ey/.atom/packages/git-grep/lib/git-grep-view.coffee:77:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "vim-mode"
    ],
    "audioBeep": false
  }
}
```

**Comment by erykpiast** [comment]
I got exactly the same error.

**Atom Version:** 1.2.4
**System:** Windows 7 (build 7601)
**Thrown From:** git-grep package, v0.9.0

**Comment by ptanov** [comment]
I got exactly the same error when starting atom.

**Atom Version**: 1.3.3
**System**: Ubuntu 15.04
**Thrown From**: [git-grep](git://github.com/mizchi/atom-git-grep) package, v0.9.0

### Stack Trace

Failed to load the git-grep package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:8:3
    at Object.<anonymous> (<anonymous>:8:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (<anonymous>:1:15)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:663:34)
    at /usr/share/atom/resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:390:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:682:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "w3c-validation",
      "incremental-search",
      "atom-terminal-panel",
      "grunt-runner",
      "language-mustache",
      "autosave",
      "deprecation-cop",
      "language-clojure",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "ide-flow"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      "build",
      "dist",
      "target",
      ".buildtmp",
      "coverage",
      "app/libs",
      "app/bower_components",
      "node_modules",
      ".tmp",
      "tags"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
angularjs, v0.3.3
atom-color-highlight, v3.0.9
atom-ternjs, v0.12.2
autoclose-html, v0.19.0
custom-title, v1.0.1
emmet, v2.3.17
file-types, v0.5.1
git-grep, v0.9.0
hex, v0.6.2
highlight-selected, v0.11.1
jshint, v1.8.3
language-javascript, v0.105.0
last-cursor-position, v0.9.0
local-history, v3.2.3
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
navigate, v0.1.13
pigments, v0.19.6
project-manager, v2.7.2
save-session, v0.16.0
symbol-gen, v1.0.0

# Dev
No dev packages
```

**Comment by mslinn** [comment]
I get this too. Is there no solution?

**Comment by kingjr** [comment]
Same error with ubuntu 14.04 and fresh atom install v1.5.4 with deb binary release, could we re-open the issue?

**Comment by jazzzz** [comment]
`git-grep` uses old atom APIs, I tried to migrate it, but I don't know enough of atom to make it.

**Comment by gyarra** [comment]
+1

**Comment by serenitus** [comment]
I get this too on Atom 1.7.0 OS X, El Capitan
