### ISSUE TITLE
Error installing git-grep

### ISSUE THREAD

**Issue by ehsan** [mizchi/atom-git-grep#14]
[Enter steps to reproduce below:]
1. I tried to install git-grep on Windows.

**Atom Version**: 1.4.3
**System**: Microsoft Windows Server 2012 Standard
**Thrown From**: [git-grep](git://github.com/mizchi/atom-git-grep) package, v0.9.0
### Stack Trace

Failed to load the git-grep package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/ehsan/.atom/packages/git-grep/lib/git-grep-view.coffee:1:1)
    at file:///C:/Users/ehsan/.atom/packages/git-grep/lib/git-grep-view.coffee:8:3
    at Object.<anonymous> (file:///C:/Users/ehsan/.atom/packages/git-grep/lib/git-grep-view.coffee:8:3)
    at Object.<anonymous> (file:///C:/Users/ehsan/.atom/packages/git-grep/lib/git-grep-view.coffee:1:1)
    at Module._compile (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/ehsan/.atom/packages/git-grep/lib/git-grep.coffee:1:15)
    at Object.<anonymous> (file:///C:/Users/ehsan/.atom/packages/git-grep/lib/git-grep.coffee:1:1)
    at Module._compile (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:722:27)
    at C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package-manager.js:522:30)
    at C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\ehsan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -2:41.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:41.9.0 blur (atom-text-editor.editor.mini.is-focused)
     -2:41.4.0 ex-mode:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:41.4.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:41.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:41.3.0 blur (atom-text-editor.editor.mini.is-focused)
  2x -2:40.6.0 core:confirm (atom-pane.pane.active)
  4x -2:36.9.0 blur (atom-pane.pane.active)
     -2:25.1.0 git-diff:move-to-next-diff (ul.list-inline.tab-bar.inset-panel)
  3x -2:22.4.0 blur (ul.list-inline.tab-bar.inset-panel)
     -1:57.3.0 git-diff:toggle-diff-list (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:57.1.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:46.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 16x -1:46.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -1:10.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:45.1.0 blur (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
ex-mode, v0.8.0
git-grep, v0.9.0
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by rubycut** [comment]
same error on mac.

**Comment by ghost** [comment]
duplicate of #13
