### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ehabkost** [mizchi/atom-git-grep#17]
Just installing git-grep 0.9.0 throws this error.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: "Fedora release
**Thrown From**: [git-grep](git://github.com/mizchi/atom-git-grep) package 0.9.0

### Stack Trace

Failed to load the git-grep package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/git-grep/lib/git-grep-view.coffee:1:1)
    at /packages/git-grep/lib/git-grep-view.coffee:7:7
    at /packages/git-grep/lib/git-grep-view.coffee:43:12)
    at /packages/git-grep/lib/git-grep-view.coffee:1:1)
    at /packages/git-grep/lib/git-grep-view.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/git-grep/lib/git-grep.coffee:1:15)
    at /packages/git-grep/lib/git-grep.coffee:1:1)
    at /packages/git-grep/lib/git-grep.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:903:35)
    at /usr/share/atom/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:617:16)
    at PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:550:25)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:684:23)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -0:44.4.0 project-find:show (input.hidden-input)
     -0:43.9.0 core:confirm (input.hidden-input)
     -0:39.2.0 core:move-up (div.results-view.focusable-panel)
     -0:38.9.0 core:move-down (div.results-view.focusable-panel)
     -0:38.1.0 core:confirm (div.results-view.focusable-panel)
     -0:37.3.0 core:move-down (input.hidden-input)
  7x -0:36.8.0 core:move-up (input.hidden-input)
  8x -0:36.2.0 core:move-down (input.hidden-input)
     -0:34.7.0 intentions:highlight (input.hidden-input)
     -0:34.5.0 pane:show-previous-item (input.hidden-input)
     -0:20.5.0 command-palette:toggle (div.results-view.focusable-panel)
     -0:19.9.0 core:backspace (input.hidden-input)
     -0:17.5.0 core:move-down (input.hidden-input)
     -0:17 core:confirm (input.hidden-input)
     -0:17 settings-view:install-packages-and-themes (div.results-view.focusable-panel)
     -0:13.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
auto-detect-indentation 1.3.0 
build 0.69.0 
build-make 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
file-watcher 1.2.6 
fonts 3.0.3 
git-grep 0.9.0 
intentions 1.1.5 
language-diff 0.7.0 
linter 2.2.0 
linter-ui-default 1.6.10 
magic-reflow 0.3.0 
trailing-spaces 0.4.0 
```

**Comment by ehabkost** [comment]
Still reproducible on Atom 1.28.2.

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: "Fedora release
**Thrown From**: [git-grep](git://github.com/mizchi/atom-git-grep) package 0.9.0


### Stack Trace

Failed to load the git-grep package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/git-grep/lib/git-grep-view.coffee:1:1)
    at /packages/git-grep/lib/git-grep-view.coffee:7:7
    at /packages/git-grep/lib/git-grep-view.coffee:43:12)
    at /packages/git-grep/lib/git-grep-view.coffee:1:1)
    at /packages/git-grep/lib/git-grep-view.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/git-grep/lib/git-grep.coffee:1:15)
    at /packages/git-grep/lib/git-grep.coffee:1:1)
    at /packages/git-grep/lib/git-grep.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:782:33)
    at measure (/usr/share/atom/resources/app/src/package.js:143:22)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at Package.load (/usr/share/atom/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:618:16)
    at config.transact (/usr/share/atom/resources/app/src/package-manager.js:531:20)
    at Config.transact (/usr/share/atom/resources/app/src/config.js:819:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-ctags 5.1.2 
atom-terminal 0.8.0 
auto-detect-indentation 1.3.0 
autocomplete 0.47.0 
autocomplete-ctags 0.4.1 
autocomplete-python 1.10.5 
build 0.70.0 
build-make 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
file-watcher 1.2.6 
fonts 3.1.0 
git-blame 1.7.0 
git-grep 0.9.0 
intentions 1.1.5 
language-diff 0.7.0 
language-robot-framework 2.2.0 
linter 2.2.0 
linter-ui-default 1.7.1 
magic-reflow 0.3.0 
markdown-preview-plus 2.4.16 
sort-lines 0.18.0 
```
