### ISSUE TITLE
Use new api calls

### ISSUE THREAD

**Issue by zimme** [mizchi/atom-git-grep#4]
Please upgrade package to use the new api :+1:

**Comment by Deathgazeroo** [comment]
bump!

**Comment by Deathgazeroo** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [git-grep](git://github.com/mizchi/atom-git-grep) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/deathgazer/.atom/packages/git-grep/lib/git-grep.coffee:20

TypeError: Cannot read property 'path' of undefined
  at Object.module.exports.grep (/Users/deathgazer/.atom/packages/git-grep/lib/git-grep.coffee:20:45)
  at atom-workspace.<anonymous> (/Users/deathgazer/.atom/packages/git-grep/lib/git-grep.coffee:12:53)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -5:01.9 core:move-left (atom-text-editor.editor.is-focused)
     -4:57.7 project-manager:toggle (atom-text-editor.editor.is-focused)
  3x -4:53.0 core:backspace (atom-text-editor.editor.mini)
     -4:51.1 core:confirm (atom-text-editor.editor.mini)
     -4:48.7 project-manager:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -4:47.5 core:confirm (atom-text-editor.editor.mini)
     -3:30.3 git-grep:grep (atom-text-editor.editor.is-focused)
     -1:54.4 core:confirm (atom-text-editor.editor.mini)
  2x -1:33.6 core:backspace (atom-text-editor.editor.mini)
     -1:32.6 core:confirm (atom-text-editor.editor.mini)
  4x -1:07.5 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:13.7 core:save (atom-text-editor.editor)
     -0:03.8 editor:select-line (atom-text-editor.editor.is-focused)
     -0:03.3 find-and-replace:find-next (atom-text-editor.editor.is-focused)
  2x -0:02.2 core:move-down (atom-text-editor.editor.is-focused)
     -0:00.5 git-grep:grep (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/Users/home/deathgazer/multisite"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
git-grep, v0.7.0
linter, v0.11.1
linter-phpcs, v0.0.12
open-last-project, v0.3.4
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by mizchi** [comment]
Oops, I will fix soon

**Comment by Deathgazeroo** [comment]
Nice :)
25 lut 2015 21:56 "Koutaro Chikuba" <notifications@github.com> napisa³(a):

**Comment by bprosnitz** [comment]
I also get a "deprecated selector warning":
keymaps/git-grep.cson
  Use the `atom-workspace` tag instead of the `workspace` class.

Was this also a recent api change?

**Comment by mizchi** [comment]
Sorry I catched a bad cold last week. I'll do it this weekend

**Comment by zimme** [comment]
:+1:
