### ISSUE TITLE
git-grep no longer works due to deprecation of apis.

### ISSUE THREAD

**Issue by petey** [mizchi/atom-git-grep#6]
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement

Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11
Object.activate - ~/.atom/packages/git-grep/lib/git-grep.coffee:13:9

Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11
GitGrepDialog.attach - ~/.atom/packages/git-grep/lib/git-grep-dialog-view.coffee:21:9

Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11
GitGrepDialog.close - ~/.atom/packages/git-grep/lib/git-grep-dialog-view.coffee:27:9

keymaps/git-grep.cson
Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by mizchi** [comment]
Thx, I will fix later

**Comment by deiga** [comment]
Please fix sooner than later :) 

The package doesn't load anymore

**Atom Version**: 0.199.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [git-grep](git://github.com/mizchi/atom-git-grep) package, v0.9.0

### Stack Trace

Failed to load the git-grep package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/timosand/Dropbox/atom/packages/git-grep/lib/git-grep-view.coffee:4:199)
    at /Users/timosand/Dropbox/atom/packages/git-grep/lib/git-grep-view.coffee:15:5
    at Object.<anonymous> (/Users/timosand/Dropbox/atom/packages/git-grep/lib/git-grep-view.coffee:75:5)
    at Object.<anonymous> (/Users/timosand/Dropbox/atom/packages/git-grep/lib/git-grep-view.coffee:77:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/timosand/Dropbox/atom/packages/git-grep/lib/git-grep.coffee:4:17)
    at Object.<anonymous> (/Users/timosand/Dropbox/atom/packages/git-grep/lib/git-grep.coffee:120:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-ctags",
      "feedback",
      "minimap",
      "run-command",
      "ruby-string-interpolation",
      "branch-status",
      "atom-lint",
      "subword-navigation",
      "terminal-status",
      "atom-color-highlight"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-light-syntax"
    ],
    "projectHome": "/Users/timosand/Dropbox/Documents/Projects",
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".codekit-cache",
      "bower_components",
      "node_modules",
      "*~"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atom-alignment, v0.12.1
auto-indent, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.17.0
autocomplete-snippets, v1.6.1
change-case, v0.5.1
cucumber, v0.5.0
cut-line, v0.10.0
editorconfig, v1.0.0
emmet, v2.3.9
error-status, v0.3.3
file-icons, v1.5.5
gistom, v0.4.8
git-grep, v0.9.0
git-tab-status, v1.9.2
highlight-line, v0.10.2
highlight-selected, v0.9.3
indent-guide-ext, v0.1.0
language-docker, v1.1.3
language-gradle, v0.0.3
language-haml, v0.20.0
language-jade, v0.4.0
language-latex, v0.6.1
language-robot-framework, v0.7.0
latex, v0.23.4
linter, v0.12.3
linter-clojure, v0.0.4
linter-coffeelint, v0.2.3
linter-csslint, v0.0.12
linter-erb, v0.1.1
linter-jshint, v0.1.4
linter-jsonlint, v0.1.3
linter-less, v0.4.0
linter-rubocop, v0.2.6
linter-scss-lint, v0.0.14
linter-tidy, v1.0.1
linter-xmllint, v0.0.5
project-manager, v1.15.5
restore-windows, v0.4.2
rulerz, v0.2.7
ssh-config, v0.10.1
wakatime, v4.0.9

# Dev
bracket-matcher, v0.62.0
change-case, v0.4.0
tree-view, v0.132.0
```

**Comment by ezekielchentnik** [comment]
pls fix

**Comment by ezekielchentnik** [comment]
needs fixin

**Comment by jpaulin** [comment]
Reproduction steps:
1. Open Atom
2. Open Git Grep (From Packages -> git-grep) 
3. Immediately after (2) this error comes up. A red box, and
   says "Failed to activate the git-grep package"

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [git-grep](git://github.com/mizchi/atom-git-grep) package, v0.9.0

### Stack Trace

Failed to activate the git-grep package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\Johndoe\.atom\packages\git-grep\lib\git-grep-view.coffee:4:199)
    at C:\Users\Johndoe\.atom\packages\git-grep\lib\git-grep-view.coffee:15:5
    at Object.<anonymous> (C:\Users\Johndoe\.atom\packages\git-grep\lib\git-grep-view.coffee:75:5)
    at Object.<anonymous> (C:\Users\Johndoe\.atom\packages\git-grep\lib\git-grep-view.coffee:77:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\Johndoe\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
     -2:22.4.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
  9x -2:16.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:08.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:08.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:04.7.0 editor:toggle-line-comments (atom-pane.pane.active)
  2x -2:03.5.0 tree-view:toggle-focus (atom-pane.pane.active)
     -1:57.7.0 find-and-replace:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:33.6.0 settings-view:install-packages-and-themes (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:20.3.0 core:close (div.settings-view.pane-item)
     -0:04.2.0 git-grep:grep (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
angularjs, v0.3.0
emmet, v2.3.12
git-grep, v0.9.0
jshint, v1.3.9

# Dev
No dev packages
```

**Comment by steveklebanoff** [comment]
+1

**Comment by lfarcy** [comment]
+1
